use crossterm::event::{KeyCode, KeyEvent};

use crate::tui::app::{TuiAction, TuiView};

pub fn action_for_view_key(key: KeyEvent, active_view: TuiView) -> TuiAction {
    match key.code {
        KeyCode::Char('q') => TuiAction::Quit,
        KeyCode::Esc => TuiAction::Back,
        KeyCode::Char('?') => TuiAction::ShowHelp,
        KeyCode::Char('1') => TuiAction::SwitchView(TuiView::Configs),
        KeyCode::Char('2') => TuiAction::SwitchView(TuiView::Sources),
        KeyCode::Char('3') => TuiAction::SwitchView(TuiView::Tests),
        KeyCode::Char('4') | KeyCode::Char('5') => TuiAction::SwitchView(TuiView::Diagnostics),
        KeyCode::Char('j') | KeyCode::Down => TuiAction::MoveDown,
        KeyCode::Char('k') | KeyCode::Up => TuiAction::MoveUp,
        KeyCode::Char('/') => TuiAction::BeginSearch,
        KeyCode::Char('f') => TuiAction::ToggleDeletedFilter,
        KeyCode::Char('F') => TuiAction::CycleFilter,
        KeyCode::Char('P') => TuiAction::CycleProtocolFilter,
        KeyCode::Char('s') if active_view == TuiView::Tests => TuiAction::StartTestBatch,
        KeyCode::Char('c') if active_view == TuiView::Tests => TuiAction::CancelTestBatch,
        KeyCode::Char('t') if active_view == TuiView::Configs => TuiAction::StartTestBatch,
        KeyCode::Enter if active_view == TuiView::Configs => TuiAction::ToggleFocused,
        KeyCode::Char('S') if active_view == TuiView::Configs => TuiAction::RuntimeStart,
        KeyCode::Char('0') if active_view == TuiView::Configs => TuiAction::RuntimeStop,
        KeyCode::Char('R') if active_view == TuiView::Configs => TuiAction::RuntimeRestart,
        KeyCode::Char('w') if active_view == TuiView::Configs => TuiAction::RuntimeSwitch,
        KeyCode::Char('s') if active_view == TuiView::Runtime => TuiAction::RuntimeStart,
        KeyCode::Char('x') if active_view == TuiView::Runtime => TuiAction::RuntimeStop,
        KeyCode::Char('r') if active_view == TuiView::Runtime => TuiAction::RuntimeRestart,
        KeyCode::Char('w') if active_view == TuiView::Runtime => TuiAction::RuntimeSwitch,
        KeyCode::Char('r') if active_view == TuiView::Sources => TuiAction::RefreshFocusedSource,
        KeyCode::Char('R') if active_view == TuiView::Sources => TuiAction::RefreshAllSources,
        KeyCode::Char('i') if active_view == TuiView::Sources => TuiAction::OpenImportModal,
        KeyCode::Char('n') if active_view == TuiView::Sources => TuiAction::OpenRenameModal,
        KeyCode::Char('d') if active_view == TuiView::Sources => TuiAction::RequestDeleteSource,
        KeyCode::Char('y') if active_view == TuiView::Sources => TuiAction::OpenQrFocused,
        KeyCode::Char('c') if active_view == TuiView::Sources => TuiAction::CopyFocused,
        KeyCode::Char('u') if active_view == TuiView::Sources => TuiAction::OpenQrApiUrl,
        KeyCode::Char('U') if active_view == TuiView::Sources => TuiAction::CopyApiUrl,
        KeyCode::Char('s') => TuiAction::CycleSort,
        KeyCode::Char(' ') => TuiAction::SelectFocused,
        KeyCode::Char('e') => TuiAction::EnableFocused,
        KeyCode::Char('E') if active_view == TuiView::Configs => TuiAction::EnableSelected,
        KeyCode::Char('x') => TuiAction::DisableFocused,
        KeyCode::Char('X') if active_view == TuiView::Configs => TuiAction::DisableSelected,
        KeyCode::Char('d') => TuiAction::RequestDeleteFocused,
        KeyCode::Char('r') => TuiAction::RestoreFocused,
        KeyCode::Char('D') => TuiAction::RequestPurgeFocused,
        KeyCode::Char('y') if active_view == TuiView::Configs => TuiAction::OpenQrFocused,
        KeyCode::Char('c') if active_view == TuiView::Configs => TuiAction::CopyFocused,
        KeyCode::Char('C') if active_view == TuiView::Configs => TuiAction::CopySelected,
        _ => TuiAction::None,
    }
}
