use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};

use super::super::action_for_key;
use crate::tui::app::{TuiAction, TuiView};

fn key(code: KeyCode) -> KeyEvent {
    KeyEvent::new(code, KeyModifiers::empty())
}

#[test]
fn maps_global_quit_keys() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('q')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::Quit
    );
    assert_eq!(
        action_for_key(
            KeyEvent::new(KeyCode::Char('c'), KeyModifiers::CONTROL),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::Quit
    );
}

#[test]
fn maps_view_switching_keys() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('1')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::SwitchView(TuiView::Configs)
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('3')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::SwitchView(TuiView::Tests)
    );
}

#[test]
fn maps_tab_to_next_view() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Tab),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::SwitchView(TuiView::Sources)
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Tab),
            TuiView::Tests,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::SwitchView(TuiView::Configs)
    );
}

#[test]
fn maps_navigation_and_help_keys() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Down),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::MoveDown
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('k')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::MoveUp
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('?')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::ShowHelp
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Esc),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::Back
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('/')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::BeginSearch
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('S')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::CycleSort
    );
}

#[test]
fn maps_enter_start_in_configs() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Enter),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::StartFocused
    );
}

#[test]
fn maps_config_test_scope_shortcuts() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('a')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::StartTestAllEnabled
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('v')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::StartTestFiltered
    );
}

#[test]
fn maps_config_action_keys() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('e')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::EnableFocused
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('x')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::DisableFocused
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('K')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::RuntimeStop
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('d')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::RequestDeleteFocused
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('D')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::RequestPurgeFocused
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('r')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::RestoreFocused
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('T')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::ToggleDeletedFilter
    );
}

#[test]
fn maps_cycle_filter_key() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('F')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::CycleFilter
    );
}

#[test]
fn maps_qr_and_copy_keys() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('y')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::OpenQrFocused
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('c')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::CopyFocused
    );
}

#[test]
fn qr_modal_open_consumes_keys() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Esc),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            true
        ),
        TuiAction::Back
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('q')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            true
        ),
        TuiAction::Back
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('s')),
            TuiView::Configs,
            false,
            false,
            false,
            false,
            true
        ),
        TuiAction::None
    );
}

#[test]
fn maps_sources_view_actions() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('r')),
            TuiView::Sources,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::RefreshFocusedSource
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('R')),
            TuiView::Sources,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::RefreshAllSources
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('i')),
            TuiView::Sources,
            false,
            false,
            false,
            false,
            false
        ),
        TuiAction::OpenImportModal
    );
}

#[test]
fn maps_import_modal_keys() {
    assert_eq!(
        action_for_key(
            key(KeyCode::Char('a')),
            TuiView::Sources,
            false,
            false,
            true,
            false,
            false
        ),
        TuiAction::ImportInput('a')
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Backspace),
            TuiView::Sources,
            false,
            false,
            true,
            false,
            false
        ),
        TuiAction::ImportBackspace
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Enter),
            TuiView::Sources,
            false,
            false,
            true,
            false,
            false
        ),
        TuiAction::ImportSubmit
    );
    assert_eq!(
        action_for_key(
            key(KeyCode::Esc),
            TuiView::Sources,
            false,
            false,
            true,
            false,
            false
        ),
        TuiAction::Back
    );
}
